# Site settings
title: CLAVER SUNGBIN'S BLOG
email: sungbin.kim@nhnent.com
description: 행복하자!!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username:
github_username:  sungbine

# Build settings
markdown: kramdown
