title: "Blog For Me"
author: "Sungbin"
description: "Really For ME"
#subheading: "Really cool blog about ... something"
more: "read more"
url: "http://sungbine.github.io"
#baseurl: "/" # comment out if in root directory



comments:
    disqus: "sungbin.kim"
#    isso: "comments.mysite.org"

style:
#    body: "whitesmoke"
    padding: 33%
    anchor: "#46f"
    serif-heading: true
    nav: "#181818"
#    headline: "#06f"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#222222"

markdown:    kramdown
highlighter: rouge
excerpt_separator: "\n\n\n"
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]

